### PR TITLE
GHC 8.8

### PR DESCRIPTION
**Pull request by skogsbaer**

### CODE REVIEW

**Comment by andreasabel** [comment]
Why is it necessary to drop support for ghc 8.2 and 8.0?

**Comment by skogsbaer** [comment]
> Why is it necessary to drop support for ghc 8.2 and 8.0?

It's not strictly necessary but in my opinion supporting the three most recent versions of GHC should be enough. Which GHC version do you need?

**Comment by skogsbaer** [comment]
also see #86

**Comment by ocharles** [comment]
Thanks @skogsbaer! Do you plan to publish a new version to Hackage now, too?

**Comment by andreasabel** [comment]
> > Why is it necessary to drop support for ghc 8.2 and 8.0?
> 
> It's not strictly necessary but in my opinion supporting the three most recent versions of GHC should be enough. Which GHC version do you need?

BNFC still support 7.6, which is maybe a bit on the conservative side.  Its testsuite (dependent on HTF) currently runs on 8.0-8.6 (see https://travis-ci.org/BNFC/bnfc/builds/616743921/config).  I had to drop GHC 7 there because of the `shelly` package; it would be nice too keep all versions of GHC 8.

The latest Ubuntu LTS (18.04) is still on GHC 8.0.  I guess the Ubuntu LTS is a good indicator (I myself only installed the LTS versions of Ubuntu).  

Agda supports >= 8.0, we generally follow the Ubuntu LTS.

**Comment by skogsbaer** [comment]
@andreasabel PR #89 brings back support for ghc 8.0 and 8.2.

@ocharles As soon as #88 and #89 are merge, I will release 0.14.0.0 to hackage.

**Comment by ocharles** [comment]
Thanks, I'll subscribe to those PRs for updates.

**Comment by skogsbaer** [comment]
0.14.0.0 ist now on hackage

**Comment by andreasabel** [comment]
Big thanks @skogsbaer!

**Comment by andreasabel** [comment]
Seems like the build on hackage has failed: https://matrix.hackage.haskell.org/#/package/HTF/0.14.0.0/
```
ghc: could not execute: cpphs
```

**Comment by skogsbaer** [comment]
I just release 0.14.0.1. I think the new version will address the problem.
@andreasabel I removed the travis check for ghc 8.0 because I did not want to support Cabal 1.24 (cabal version from the hackage lts snapshot for ghc 8.0.)

**Comment by skogsbaer** [comment]
0.14.0.1 builds with ghc 8.8, 8.6, 8.4, 8.2: https://matrix.hackage.haskell.org/#/package/HTF/0.14.0.1/ghc-8.0.2@1574861493

**Comment by andreasabel** [comment]
I tried 7.10.3 and 8.0.2 and `cabal install HTF` also worked.

**Comment by andreasabel** [comment]
> I tried 7.10.3 and 8.0.2 and `cabal install HTF` also worked.

Unfortunately, not on a fresh system.  It only works if a newer cabal is installed.

**Pull request merged**
